export const users = {
  name: 'users',
  color: 'bg-blue-50 border-blue-300',
  fields: [
    { name: '_id', type: 'ObjectId', constraint: 'PK, Auto-generated (maps to id uuid)' },
    { name: 'phone', type: 'String', constraint: 'Required, Unique, Index' },
    { name: 'email', type: 'String', constraint: 'Optional, Unique, Index' },
    { name: 'passwordHash', type: 'String', constraint: 'Required' },
    { name: 'profile', type: 'Object', constraint: 'Optional, JSON' },
    { name: 'isPhoneVerified', type: 'Boolean', constraint: 'Default: false' },
    { name: 'phoneVerificationToken', type: 'String', constraint: 'Optional' },
    { name: 'phoneVerificationExpiry', type: 'Date', constraint: 'Optional' },
    { name: 'isEmailVerified', type: 'Boolean', constraint: 'Default: false' },
    { name: 'emailVerificationToken', type: 'String', constraint: 'Optional' },
    { name: 'emailVerificationExpiry', type: 'Date', constraint: 'Optional' },
    { name: 'lastPasswordChange', type: 'Date', constraint: 'Optional' },
    { name: 'passwordResetToken', type: 'String', constraint: 'Optional' },
    { name: 'passwordResetExpiry', type: 'Date', constraint: 'Optional' },
    { name: 'failedLoginAttempts', type: 'Number', constraint: 'Default: 0' },
    { name: 'lockedUntil', type: 'Date', constraint: 'Optional' },
    { name: 'accountStatus', type: 'String', constraint: 'Enum: [ACTIVE, INACTIVE, SUSPENDED, DELETED], Default: ACTIVE' },
    { name: 'securityNotifications', type: 'Object', constraint: 'Optional, JSON' },
    { name: 'lastSecurityNotificationAt', type: 'Date', constraint: 'Optional' },
    { name: 'lastLoginAt', type: 'Date', constraint: 'Optional, Index' },
    { name: 'lastLogoutAt', type: 'Date', constraint: 'Optional' },
    { name: 'loginCount', type: 'Number', constraint: 'Default: 0' },
    { name: 'lastActivityAt', type: 'Date', constraint: 'Optional' },
    { name: 'deletedAt', type: 'Date', constraint: 'Optional' },
    { name: 'createdAt', type: 'Date', constraint: 'Default: Date.now()' },
    { name: 'updatedAt', type: 'Date', constraint: 'Default: Date.now(), auto-updated' },
    { name: 'role', type: 'String', constraint: 'Enum: [USER, PROVIDER, ADMIN, SUPPORT], Default: USER' }
  ],
  indexes: ['phone (unique)', 'email (unique)', 'role + accountStatus', 'lastLoginAt']
};
